#!/bin/bash

set -euxo pipefail

BAMBOO_DOWNLOAD_URL=http://product-downloads.atlassian.com/software/bamboo/downloads/atlassian-bamboo-11.0.8.tar.gz
BAMBOO_DOWNLOAD_DEST=/tmp/atlassian-bamboo-11.0.8.tar.gz
BAMBOO_DOWNLOAD_CHECKSUM=ead509de2ec8b7d304f611f8df7ae3b55f4fcf4a20dabdff7b64ae862fcff908

BAMBOO_CATALINA=/opt/atlassian/bamboo
BAMBOO_PATCH=/opt/atlassian/atlassian-bamboo.patch

wget -c $BAMBOO_DOWNLOAD_URL -O $BAMBOO_DOWNLOAD_DEST
echo -n "$BAMBOO_DOWNLOAD_CHECKSUM $BAMBOO_DOWNLOAD_DEST" | sha256sum -c -

rm -rf $BAMBOO_CATALINA
mkdir -p $BAMBOO_CATALINA
tar zxf $BAMBOO_DOWNLOAD_DEST -C $BAMBOO_CATALINA --strip-components=1

cat $BAMBOO_PATCH | patch -p1 -d /
chmod a+x $BAMBOO_CATALINA/bin/start-bamboo.sh
chmod a+x $BAMBOO_CATALINA/bin/stop-bamboo.sh
find $BAMBOO_CATALINA -type f -name '*.so' -exec chrpath -d {} \;
find $BAMBOO_CATALINA -type f -name '*.bak' -delete
find $BAMBOO_CATALINA -type f -name '*.orig' -delete
find $BAMBOO_CATALINA -type f -name '*.rej' -delete
fdupes -qnrps $BAMBOO_CATALINA

chown -Rf bamboo:bamboo $BAMBOO_CATALINA
chmod 0700 $BAMBOO_CATALINA

#DEBHELPER#

exit 0
